apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: matrix-example
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
          - git:
              repoURL: https://github.com/ponienselvan/kubeapp1.git
              directories:
                - path: "apps/*"

    # - clusters:
    #     selector:
    #       matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    spec:
      project: default
      source:
        repoURL: https://github.com/ponienselvan/kubeapp1.git
        targetRevision: HEAD
        path: "{{.path.path}}"
      destination:
        server: "{{.server}}"
    metadata:
      name: "guestbook-{{.name}}"
